jslint-org/jslint

- CHANGELOG.md
- README.md
- browser.js
- help.html
- index.html
- jslint.js
- test.js
- ci - fix expectedWarningCode not being validated.
- ci - in windows, disable git-autocrlf.
- deadcode - replace with assertion-check in function are_similar() - "if (a === b) { return true }".
- deadcode - replace with assertion-check in function are_similar() superseded by id-check - "if (Array.isArray(b)) { return false; }".
- deadcode - replace with assertion-check in function are_similar() superseded by is_weird() check - "if (a.arity === "function" && a.arity ===...c".
- jslint - add directive `test_internal_error`.
- jslint - add directive `unordered` to tolerate unordered properties and params.
- jslint - inline-document each warning with cause that can reproduce it - part 1.
- style - refactor code moving infix-operators from post-position to pre-position in multiline …
> v2021.5.27

- CHANGELOG.md
- README.md
- jslint.js
- test.js
> - bugfix - fix #282 - fail to warn trailing semicolon in `export default Object.freeze({})`.

- CHANGELOG.md
- README.md
- jslint.js
- bugfix - fix issue #282 - fail to warn trailing semicolon in `export default Object.freeze({})`.
- ci - 100% code-coverage!
- ci - auto-update changelog in README.md from CHANGELOG.md.
- ci - auto-update version numbers in README.md and jslint.js from CHANGELOG.md.
- deadcode - replace with assertion-check in function choice() - `if (char === "|") { warn... }`.
- deadcode - replace with assertion-check in function do_function() - `if (mega_mode) { warn... }`.
- deadcode - replace with assertion-check in function no_space() - `const at = (free ? ...)`.
- deadcode - replace with assertion-check in function no_space() - `if (open) {...}`.
- deadcode - replace with assertion-check in function parse_directive() - `} else if (value === "false") {...}`.
- deadcode - replace with …
> v2021.5.30 - 100% code-coverage and bugfix #282 (failure to enforce semicolon in export-statement)

- CHANGELOG.md
- README.md
- browser.js
- ci.sh
- help.html
- index.html
- jslint.js
- test.js
fixes #304, #281
- breaking-change - hardcode `const fudge = 1`
- breaking-change - remove little-used-feature allowing jslint to accept array-of-strings as source b/c internal lines-object has been changed from array-of-strings to array-of-objects.
- jslint - add eslint-like ignore-directives `/*jslint-disable*/`, `/*jslint-enable*/`, `//jslint-quiet`.
- jslint - add new warning `Unclosed directive /*jslint-disable*/.`.
2nd attempt to add ignore-directives because:
- make it easier for newcomers to onboard jslint by allowing them to selectively disable warnings for project-files they don't have time yet to fix.
- allow jslinting of rollup files that contain machine-generated-code.
- eventually get rid of "hammer" directives `/*jslint devel*/` and `/*jslint eval*/`, replacing them with …
> - jslint - add eslint-like ignore-directives `/*jslint-disable*/`, `/*jslint-enable*/`, `//jslint-quiet`.

- CHANGELOG.md
- README.md
- browser.js
- ci.sh
- jslint.js
- test.js
this pr feels cheesy/hacky but seems to get the job done and passes tests (it creates a new function-scope for each catch-block).  if someone has time to review it and come up with more elegant solution would be nice ; )
motivation:
due to buggy internet-explorer lacking scope for catch-blocks, jslint warned against the following code:
```javascript
/*jslint devel*/
let aa = 0;
try {
aa();
} catch (err) {
console.error(err);
}
try {
aa();
// warning
// Redefinition of 'err' from line 6.
} catch (err) {
console.error(err);
}
```
modern engines don't have this bug plus its PITA maintaining unique exception-name for each catch-block, when typing out a buncha successive try...catch sequences.  as bonus, jslint will now properly warn exception-names are out-of-scope when used outside of …
> remove obsolete ie-era warning about duplicate names for caught-exceptions.

- CHANGELOG.md
- README.md
- jslint.js
- breaking-change - hardcode `const fudge = 1`
- breaking-change - remove little-used-feature allowing jslint to accept array-of-strings as source b/c internal lines-object has been changed from array-of-strings to array-of-objects.
- doc - add svg changelog.
- doc - add svg package-listing.
- doc - document cli-feature to jslint entire directory.
- jslint - add eslint-like ignore-directives `/*jslint-disable*/`, `/*jslint-enable*/`, `//jslint-quiet`.
- jslint - add new warning `Directive /*jslint-disable*/ was not closed with /*jslint-enable*/.`.
- jslint - add new warning `Directive /*jslint-enable*/ was not opened with /*jslint-disable*/.`.
- jslint - remove obsolete ie-era warning about duplicate names for caught-errors.
- website - move options-ui to top of page after editor-ui
> ## v2021.6.3

- CHANGELOG.md
- jslint.js
this looks like a big pr, but its mostly just adding 4-space indents to global variables/functions, and moving them into jslint's function-scope, to remove any module-level state.
> - jslint rewrite part1 - make "stateful" variables scoped outside of jslint() "stateless" by moving them into jslint().

- CHANGELOG.md
- ci.sh
- jslint.js
- jslint - add warning for unexpected ? in example `aa=/.{0}?/`.
- jslint-refactor-2 - inline constants anticondition, bitwiseop, escapeable, and opener directly into code.
- jslint-refactor-3 - inline regexp-functions quantifier(), ranges(), klass(), choice(), directly into code.
> Jslint refactor 3 - inline constants and regexp-functions directly into code.

- CHANGELOG.md
- browser.js
- jslint.js
- test.js
- remove unnecessary variables nr.
- rename artifact-related variables a, b to let artifact_now, artifact_nxt.
- rename functions make() to token_create().
- reorganize/rename "global" variables by topical-prefixes:
artifact_xxx, export_xxx, from_xxx, import_xxx, line_xxx, mode_xxx, token_xxx
> - jslint-refactor-4 - document jslint process and each recursion-loop converted to while-loop.

- CHANGELOG.md
- help.html
- index.html
- jslint.js
- test.js
decided to re-include the nomen-directive, to make things easier for newcomers to onboard jslint.
> - directive - re-introduce `/*jslint name*/` to ignore "Bad property name" warning.

- CHANGELOG.md
- jslint.js
- test.js
- bugfix - fix off-by-one-column bug in missing-semicolon-warning.
fixes issues #316, #317.
> - bugfix - fix issue #316, #317 - jslint complains about dynamic-import.

- CHANGELOG.md
- jslint.js
- test.js
- bugfix - fix await expression/statement inside catch-statement not registered by functionage.await.
fixes #319, by removing misleading `alphabetical` label.  ascii-ordering is still maintained.
> - bugfix - fix misleading warning describing alphabetical-order instead of ascii-order.

- CHANGELOG.md
- README.md
- jslint.js
- test.js
this pr is biggest jslint-refactor to-date.
add 4-space-indent to 4000+ lines of jslint's core-logic so they can be split into 5 [mostly]-self-contained sub-functions:
```javascript
function jslint(
source = "",
option_object = empty(),
global_array = []
) {
// PHASE 1. Split <source> by newlines into <line_array>.
function phase1_split() {
<10 lines-of-code>
}
// PHASE 2. Lex <line_array> into <token_array>.
function phase2_lex()   {
<1,200 lines-of-code>
}
// PHASE 3. Parse <token_array> into <token_tree> using Pratt parsing.
function phase3_parse() {
<2,800 lines-of-code>
}
// PHASE 4. Walk <token_tree>, traversing all of the nodes of the tree. It is a
//          recursive traversal. Each node may be processed on the way down
//          (preaction) and on the way up (postaction). …
```
> - jslint-refactor-5 - split jslint-core-logic into 5-phases.

- CHANGELOG.md
- README.md
- jslint.js
- bugfix - fix await expression/statement inside catch-statement not registered by functionage.await.
- bugfix - fix cli appending slash "/" to normalized filename.
- bugfix - fix issue #316, #317 - jslint complains about dynamic-import.
- bugfix - fix misleading warning describing alphabetical-order instead of ascii-order.
- bugfix - fix off-by-one-column bug in missing-semicolon-warning.
- bugfix - fix try-catch-block complaining about "Unexpected await" inside async-function.
- directive - re-introduce `/*jslint name*/` to ignore "Bad property name" warning.
- doc - add install-screenshots.
- jslint - add new warning if case-statements are not sorted.
- jslint - add warning for unexpected ? in example `aa=/.{0}?/`.
- jslint - add warning for unexpected-expr in example `async function …
> ## v2021.6.12

- CHANGELOG.md
- browser.js
- index.html
- jslint.js
- test.js
- jslint - add new warning if const/let/var statements are not declared at top of function-scope.
- jslint - add new directive `/*jslint beta*/` - enable features currently in beta.
- bugfix - fix no-warning when exception in catch-block is unused (refactor pr #306).
this pr would fix #279 .
the solution may seem drastic, but i think its the right direction.  the new warning is behind a beta-flag (use directive `/*jslint beta*/` to enable the new warning).
essentially jslint would require all variable declarations (including `const` and `let`) to be placed at top of function-scope (or beginning of script -- after any import-statements).  this pr also contains a bit of code-refactoring to comply with the new warning.
> - jslint - add new directive `/*jslint variable*/` - allow unordered variable-declarations that are not at top of function-scope.

- CHANGELOG.md
- browser.js
- ci.sh
- jslint.js
- test.js
this pr tightens jslint to require variables declared at top-of-function-scope/global-scope to be ordered, e.g.:
```javascript
/*jslint beta*/
var bb = 0;
var aa = 0;
// warning
// 1 Expected var 'aa' before var 'bb'. // line 3, column 1
//     var aa = 0;
```
currently behind `beta` flag.
demo of pr @ https://kaizhu256.github.io/jslint/branch-alpha/index.html
> - jslint - add new warning if const/let/var statements are unordered.

- CHANGELOG.md
- README.md
- browser.js
- ci.sh
- jslint.js
- bugfix - fix global_list being ignored by jslint.
- bugfix - fix no-warning when exception in catch-block is unused.
- ci - migrate ci-scripts from cjs to esm.
- cli - add env-variable \$JSLINT_BETA.
- jslint - add new directive `/*jslint beta*/` - enable features currently in beta.
- jslint - add new directive `/*jslint variable*/` - allow unordered variable-declarations that are not at top of function-scope.
- jslint - add new warning if const/let/var statements are not declared at top of function-scope.
- jslint - add new warning if const/let/var statements are unordered.
- website - invalidate url-cache with each deployment.
- website - replace .png logo with .svg logo.
- website - replace current-editor with CodeMirror-editor and change programming-font-family from `Programma` to …
> ## v2021.6.22

- .gitignore
- CHANGELOG.md
- README.md
- browser.mjs
- ci.sh
- function.html
- index.html
- jslint.mjs
- package.json
- test.mjs
- jslint - rename files *.js to *.mjs for better integration with nodejs.
this pr renames all *.js files to *.mjs so nodejs can import them without any configuration-hints (e.g. package.json).
also remove user-confusion when downloading/installing jslint, that it might be a .cjs file.
the ci will provide a cjs-variant at jslint.com (https://www.jslint.com/jslint.cjs).
for legacy installations, the old .js variant is available at website as well (https://www.jslint.com/jslint.js).
preview of .cjs and .mjs variants available at:
- https://github.com/jslint-org/jslint/blob/gh-pages/branch-alpha/jslint.cjs
- https://github.com/jslint-org/jslint/blob/gh-pages/branch-alpha/jslint.mjs
> - ci - include explicit commonjs (jslint.cjs) and es-module (jslint.mjs) variants of jslint.

- CHANGELOG.md
- browser.mjs
- ci.sh
- index.html
- jslint.mjs
- test.mjs
- jslint - add "jslint_" prefix to global variables.
- website - add search-param "mode_debug=1".
i don't necessarily agree with 2-space indent, but directive `/*jslint indent2*/` would make jslint more accessible to existing/legacy projects using 2-space indent.
> - jslint - reintroduce directive `/*jslint indent2*/` - allow 2-space indent.

- CHANGELOG.md
- asset-codemirror-rollup.css
- asset-codemirror-rollup.js
- browser.mjs
- ci.sh
- index.html
- jslint.mjs
- test.mjs
- website - create codemirror-plugin to highlight jslint-warnings in editor.
pr fixes #272.
the following code with cyclic function-calls is now allowed in jslint:
```javascript
/*jslint node*/
function foo() {
console.log("foo");
setTimeout(bar, 1000);
}
function bar() {
console.log("bar");
setTimeout(foo, 1000);
}
foo();
```
also lays future groundwork for jslint to warn if function-declarations are unordered (similar to unordered vars).
> - jslint - disable out-of-scope warning for function-statements.

- CHANGELOG.md
- LICENSE
- README.md
- browser.mjs
- ci.sh
- jslint.mjs
- test.mjs
- breaking-change - rename files *.js to *.mjs for better integration with nodejs.
- ci - auto-screenshot example-shell-commands in README.md.
- ci - include explicit commonjs (jslint.cjs) and es-module (jslint.mjs) variants of jslint.
- jslint - disable out-of-scope warning for functions.
- jslint - reintroduce directive `/*jslint indent2*/` - allow 2-space indent.
- license - change license to public-domain/unlicense.
- website - create codemirror-plugin to highlight jslint-warnings in editor.
> # v2021.6.30

- CHANGELOG.md
- jslint.mjs
- test.mjs
- tests - test column position in warnings are correct.
- bugfix - fix jslint not warning about function-redefinition when function is defined inside a call.
revamp cause-based testing with additional instrumentation to validate a warning's:
1. calling-function
2. artifact
3. column-position
example:
```diff
// old inline test.
-// cause: "0a"
// new inline test with extra caller/code/artifact/column instrumentation.
+// test_cause:
+// ["0a", "lex_number", "unexpected_a_after_b", "0", 2]
```
> - tests - revamp cause-based testing with more robust instrumentation.

- .github/workflows/ci.yml
- .github/workflows/on-pull-request.yml
- CHANGELOG.md
- jslint.mjs
- test.mjs
- jslint - add new beta-warning if functions are unordered.
- jslint-revamp - rearrange functions in jslint.mjs to comply with ordered-functions beta-warning.
- ci - allow manually triggering ci.
follup to pr #331.
this is a big pr, not because of code-changes, but because all named-functions have been moved to top of function-scope and ordered in ascii-order.  `jslint.mjs` has ~200 named-functions and most were moved to different locations after re-ordering.
the new accompanying warning is hidden behind `/*jslint beta*/` directive and not intended for normal-users.  use beta-directive if you want to enable it:
```
/*jslint beta*/
function bb() {
return;
}
function aa() {
return;
}
//  1. Expected function 'aa' to be ordered before function 'bb'. // line 5, column 10
// function aa() { …
```
> - jslint - add new beta-warning if functions are unordered.

- CHANGELOG.md
- README.md
- browser.mjs
- jslint.mjs
- bugfix - fix jslint not warning about function-redefinition when function is defined inside a call.
- bugfix - fix website crashing when linting pure json-object.
- ci - fix race-condition when inlining css.
- doc - update README.md with links to archived web-demos.
- jslint - add new beta-warning against redefining global-variables.
- jslint - add new beta-warning if functions are unordered.
- jslint - add new warning disallowing string-literal as property-name, e.g. {`aa`:0}.
- jslint - comment out shebang in jslint.mjs so older ios devices can use website.
- jslint - deprecate directive `/*jslint eval*/` - use `//jslint-quiet` instead.
- jslint-revamp - rearrange functions in jslint.mjs to comply with ordered-functions beta-warning.
- jslint-revamp - revamp cause-based testing with …
> # v2021.7.24

- browser.mjs
Users can view how many errors and functions they have at a glance with "notifications".
Should there be a space between the Report name and the number?
> Lint report "notifications"

- CHANGELOG.md
- browser.mjs
- jslint.mjs
this pr improves jslint ergonomics with:
- testing frameworks like mocha, e.g.:
```js
/*jslint node*/
/*global beforeEach, describe*/
describe("hooks", function () {
beforeEach(function () {
// runs before each test in this block
return;
});
// test cases
});
```
- es-modules using global browser-apis, e.g.:
```js
/*jslint browser*/
/*global indexedDB*/
import foo from "bar";
let request = indexedDB.open(foo.name);
export default Object.freeze(request);
```
demo of pr available @ https://kaizhu256.github.io/jslint/branch-sandbox/index.html
> - warning - disable un-ergonomic warnings restricting directive-global (missing_browser and unexpected_directive_a).

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- jslint.mjs
- warning - disable un-ergonomic warnings restricting directive-global (missing_browser and unexpected_directive_a).
- fs - rename file ci.sh to jslint_ci.sh.
- license - add codemirror license to rollup-assets.
- website - display number of warnings, properties, functions in report.
- website - fix uiLoader getting hidden behind highlighted text.
> # v2021.8.20

- CHANGELOG.md
- README.md
- browser.mjs
- index.html
- jslint.mjs
- jslint.vim
- test.mjs
the `debug` directive is used by jslint-developers to diagnose internal bugs.
renaming it to `trace` to prevent user-confusion with similarly named directived `devel` (that's completely unrelated).
> - jslint - rename little-used directive `debug` to `trace` to avoid confusion with non-related directive `devel`.

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- test.mjs
this pr adds istanbul/c8 like options `--exclude=aa,bb`, `--exclude-node-modules=false`,  and `--include=aa,bb` to command `v8_coverage_report`.  file-globbing is not currently supported, but planned for a future-pr.
```js
node ../jslint.mjs \
v8_coverage_report=../.artifact/coverage_sqlite3_sh/ \
--exclude-node-modules=true \
--exclude=test/foo.js,test/bar.js \
--exclude=test/baz.js \
--include=lib/sqlite3-binding.js,lib/sqlite3.js \
--include=lib/trace.js \
npm run test
```
> - coverage - add cli-options `--exclude=aa,bb`, `--exclude-node-modules=false`, `--include=aa,bb`

- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- package.json
- test.mjs
- jslint - add top-level-await support
- ci - deprecate/remove jslint.cjs from ci
- coverage - add cli-options `--exclude=aa,bb`, `--exclude-node-modules=false`, `--include=aa,bb`
- coverage - dedupe coverage-logic now applied when only one script passed
- npm - add file .npmignore
- website - add clickable-links to editor-code in report-warnings and report-functions
> V2021.11.20 - add top-level-await support

- CHANGELOG.md
- jslint.cjs
- jslint.mjs
- jslint_ci.sh
- package.json
- test.mjs
- bugfix - fix issue #379 - cryptic-warning against using "delete" keyword in fat-arrow.
- update commonjs-wrapper jslint.cjs to load jslint in strict-mode.
online-demo of this pr available @ https://kaizhu256.github.io/jslint/branch-alpha/index.html
> - bugfix - fix cryptic-warning against using "delete" keyword in fat-arrow.

- CHANGELOG.md
- jslint.mjs
- test.mjs
this pr fixes issue #382.
the issue is an edge-case where jslint fails to properly detect destructured fat-arrows and warn against them.
Fat-arrows are now detected by keeping a list of most recent "(" tokens at any
given depth. When a "=>" token is encountered, the most recent "(" token at
current depth is marked as a fat-arrow.
> - bugfix - fix warnings against destructured fart

- CHANGELOG.md
- jslint.mjs
this pr fixes #382, changing the cryptic-warning against destructured fat-arrows to something more readable.
from:
```
Expected 'function' before '('.
pickOne: ({one}) => one
Expected '{' and instead saw '=>'.
pickOne: ({one}) => one
```
to:
```
Use 'function (...)', not '(...) =>' when arrow function becomes too complicated.
pickOne: ({one}) => one
```
> - bugfix - make fart-related warnings more readable

- CHANGELOG.md
- README.md
- jslint.mjs
- package.json
- test - migrate all tests to use jstestDescribe(), jstestIt()
- fs - rename jslint-wrapper-files to jslint_wrapper_xxx.xxx
- bugfix - fix issue #382 - make fart-related warnings more readable
- bugfix - fix issue #382 - fix warnings against destructured fart
- bugfix - fix issue #379 - warn against naked-statement in fart.
- update commonjs-wrapper jslint.cjs to load jslint in strict-mode.
> # v2022.2.20

- CHANGELOG.md
- jslint.mjs
- test.mjs
- jslint - move regexp-literals back to module-level so they are explicitly cached, to improve performance
this pr adds
- numeric-separator support which improves code-readability
- warnings against illegally-placed numeric-separators
> - jslint - add numeric-separators support

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- package.json
- test.mjs
- website - use localStorage to persist jslint-options selected in ui
- website - add optional debug-mode to use sessionStorage to persist jslint-globals and jslint-source from ui
- jslint - add numeric-separator support
- jslint - move regexp-literals to module-level so they are explicitly cached, to improve performance
- ci - add check for package.json.fileCount
> # v2022.3.30

- .ci.sh
- CHANGELOG.md
- README.md
- asset_codemirror_rollup.js
- index.html
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_codemirror.html
- jslint_wrapper_codemirror.js
- jslint_wrapper_vscode.js
- package.json
- test.mjs
1. this pr exposes the internal code used by jslint to integrate with codemirror editor, for public use
1. Download and save [`jslint.mjs`](https://www.jslint.com/jslint.mjs), [`jslint_wrapper_codemirror.js`](https://www.jslint.com/jslint_wrapper_codemirror.js)
2. Create and serve static html-page below:
```shell 
#!/bin/sh
mkdir -p .artifact/
cp jslint.mjs .artifact/
cp jslint_wrapper_codemirror.js .artifact/
printf '
<!DOCTYPE html>
<html lang="en">
<head>
<title>CodeMirror: JSLint Demo</title>
<link rel="stylesheet" href="https://codemirror.net/lib/codemirror.css">
<link rel="stylesheet" href="https://codemirror.net/addon/lint/lint.css">
<style>
body {
background: lightgray;
color: darkslategray;
font-family: sans-serif;
margin: 0;
padding: 0 20px;
}
body > * {
margin: 20px 0 0 0; …
```
> - wrapper - add jslint-addon for codemirror

- .ci.sh
- .gitignore
- .npmignore
- CHANGELOG.md
- README.md
- index.html
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_cjs.cjs
- jslint_wrapper_codemirror.js
- jslint_wrapper_vim.vim
- jslint_wrapper_vscode.js
- test.mjs
this pr revamps jslint's v8-coverage-report functionality to use glob-pattern-matching when excluding coverage-files, rather than list of explicit filenames:
```shell
node ../jslint.mjs \
v8_coverage_report=../.artifact/coverage_sqlite3_sh/ \
--exclude=**/node_modules/ \
--exclude=node_modules/ \
--exclude=tes?/ \
--exclude=tes[!0-9A-Z_a-z-]/ \
--exclude=tes[0-9A-Z_a-z-]/ \
--exclude=tes[^0-9A-Z_a-z-]/ \
--exclude=test/**/*.js \
--exclude=test/suppor*/*elper.js \
--exclude=test/suppor?/?elper.js \
--exclude=test/support/helper.js \
--include=**/*.cjs \
--include=**/*.js \
--include=**/*.mjs \
--include=li*/*.js \
--include=li?/*.js \
--include=lib/* \
--include=lib/**/*.js \
--include=lib/*.js \
--include=lib/sqlite3.js \
npm run test
```
> coverage-report - add function globPathExclude() to revamp coverage-report to exclude files using glob-pattern-matching

- .github/workflows/ci.yml
- .github/workflows/on_pull_request.yml
- CHANGELOG.md
- README.md
- jslint.mjs
- package.json
- coverage-report - disable default-coverage of directory `node_modules`, but allow override with cli-option `--include-node-modules=1`
- coverage-report - add function globExclude() to revamp coverage-report to exclude files using glob-pattern-matching
- add codemirror-example-file jslint_wrapper_codemirror.html
- update codemirror-editor to v5.65.3
- wrapper - add jslint-addon for codemirror
- allow jslint.mjs to auto-export itself to globalThis when given search-param `?window_jslint=1`
- wrapper - add jslint-extension for vscode
- bugfix - fix jslint falsely believing megastring literals `0` and `1` are similar
- bugfix - fix function jstestOnExit() from exiting prematurely and suppressing additional error-messages
> # v2022.5.20

- .ci.sh
- CHANGELOG.md
- jslint.mjs
- jslint_ci.sh
- package.json
- allow array-literals to directly call [...].flat() and [...].flatMap()
this pr fixes jslint from crashing in screenshot below
> - bugfix - fix jslint not-recognizing option-chaining when comparing operands of binary operator

- CHANGELOG.md
- README.md
- asset_codemirror_rollup.js
- help.html
- index.html
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_codemirror.html
- jslint_wrapper_codemirror.js
- test.mjs
- directive - add new directive `subscript` for linting of scripts targeting Google Closure Compiler
```js
/*jslint subscript*/
let aa = {};
// allow identifier in subscript-notation to prevent Google Closure Compiler
// from over-optimizing/renaming/mangling property-name "bb"
aa["bb"] = 1;
```
- warning - relax warning about missing `catch` in `try...finally` statement
```js
/*jslint browser*/
/*global _free, _malloc, manipulatePointer*/
function webassemblyFoo() {
let pointer;
try {
pointer = _malloc(1024);
manipulatePointer(pointer);
} finally {
// we want to cleanup pointer to prevent memory-leak,
// but want the error to continue being raised
_free(pointer);
}
}
function uiFoo() {
try {
webassemblyFoo();
} catch (err) {
window.alert(err);
}
}
```
- jslint - allow aliases `evil, …
> - directive - add new directive `subscript` for linting of scripts targeting Google Closure Compiler

- CHANGELOG.md
- jslint.mjs
- test.mjs
this pr fixes jslint misidentifying expression after await-keyword as a statement
> - bugfix - fix expression after "await" mis-identified as statement

- .ci.sh
- CHANGELOG.md
- README.md
- index.html
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_codemirror.js
- jslint_wrapper_vscode.js
- package.json
- test.mjs
- vscode - add extra contextmenu commands "JSLint - Do Not Lint Selected Region", "JSLint - Ignore Current Line"
1. this pr documents jslint's most common directives in README.md
- directive `//jslint-quiet` is renamed to `//jslint-ignore-line`, but the old directive is kept as an alias for backwards-compat
3. update vscode-plugin with extra commands to disable jslint on per-region and per-line basis
> - doc - document jslint directives

- .ci.sh
- CHANGELOG.md
- README.md
- help.html
- index.html
- jslint.mjs
- package.json
- test.mjs
fixes #413 (and re-fixes #382).
- this pr adds new directive `/*jslint fart*/` which allows destructing in fat-arrows, and `{...}` statement-blocks.
- the fat-arrow parser/walker has been cleaned up to better align with how regular-functions are parsed.
> - directive - add new directive `fart` to allow complex fat-arrow

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- package.json
- ci - bugfix - fix ci-shell-function shGithubFileUpload unable to upload new asset
- ci - auto-create asset_image_logo_512.png from asset_image_logo_512.html
- bugfix - fix shell-function shGithubCheckoutRemote not able to checkout trusted-files in non-alpha branches
- jslint-ci - revamp auto-updating and add shell-function shGithubCheckoutRemote
- test - print time-finished after test-run
- jslint - hide warning about unordered case-statements behind beta-flag
- ci - bugfix - update shell-function shCiBase() to handle undefined fileMain
- ci - auto-update version-number in main mjs-module
- ci - update shell-function shDirHttplinkValidate() to ignore insecure-links http://127.0.0.1, http://localhost
> # v2023.1.29

- index.html
Open links in new tabs to prevent textarea content from getting wiped.
Closes #345
> Open links in new tab

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- package.json
- vscode - Add manual lint-on-save command to vscode-jslint extension.
- ci - add custom-shell-ci hooks to script jslint_ci.sh: shCiArtifactUploadCustom() shCiBaseCustom() shCiBaseCustom2() shCiLintCustom() shCiLintCustom2() shCiNpmPublishCustom() shCiPreCustom() shCiPreCustom2()
- ci - housekeeping of ci-file jslint_ci.sh
- ci - update shell-function shGitCommitPushOrSquash() to be able to save to specified filename
- ci - remove little-used shell-function shCiBranchPromote()
> # v2023.4.29

- CHANGELOG.md
- jslint.mjs
- jslint_ci.sh
> - jslint - Add grammar for regexp-named-capture-group and regexp-named-backreference.

- CHANGELOG.md
- jslint.mjs
- jslint_ci.sh
- test.mjs
- Fixes #438.
- fatal error due to no grammar for `export async function ...`.
- jslint will still warn about using `Object.freeze(...)` but at least its no longer a fatal error, and can be suppressed with `//jslint-ignore-line`
- This PR additionally adds warning/check that exported properties are sorted in ascii-order
> Branch export async function

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- package.json
- jslint - Check exported properties are ordered.
- jslint - Add grammar for "export async function ...".
- python - Add shell-function shLintPython().
- jslint - Add grammar for regexp-named-capture-group and regexp-named-backreference.
- jslint - Add grammar for side-effect import-statement.
- ci - Rename shell-function shRawLibFetch() to shRollupFetch().
- doc - document devop procedures to maintain jslint-repo
> # v2023.5.23

- .ci.sh
- .github/workflows/ci.yml
- .github/workflows/on_pull_request.yml
- .github/workflows/publish.yml
- .gitignore
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_vim.vim
- package.json
- jslint - bugfix - Update file jslint_wrapper_vim.vim to fix broken vim-link when linting shell-files.
- ci - add custom-shell-ci hooks to script jslint_ci.sh: shCiPublishNpmCustom() shCiPublishPypiCustom()
> # v2023.10.24

- .ci.sh
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- jslint_wrapper_vim.vim
- package.json
Fixes #455 .
- vim - Allow installing vim-plugin to any directory, instead of hardcoded to ~/.vim/.
This PR will allow you to install vim-plugin to custom-directory, e.g:
- save [`jslint.mjs`](https://www.jslint.com/jslint.mjs), [`jslint_wrapper_vim.vim`](https://www.jslint.com/jslint_wrapper_vim.vim) to directory `~/vimfiles/`
- vim-command `:source ~/vimfiles/jslint_wrapper_vim.vim`
Additionally, this PR will:
- ci - Update github-ci for actions/cache, actions/setup-python from nodejs v16 to nodejs v20.
- ci - Update shell-function shRollupFetch() to fix blank date-committed.
- ci - bugfix - Fix google-chrome unable to create screenshot because user-data-dir is /dev/null.
> Branch vim windows install

- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_wrapper_vim.vim
this PR will additionally fix #455 (2nd attempt):
- vim - Allow installing vim-plugin to any directory, instead of hardcoded to ~/.vim/. - part2
> - test - Update test-function jstestDescribe() to wait awhile for imports to initialize before running tests.

- .ci.sh
- CHANGELOG.md
- jslint.mjs
- test.mjs
- jslint - Allow destructuring-assignment after function-definition.
This PR relaxes warning about `[]` operator appearing after a function definition, due to it now being legal-syntax for destructuring-assignment, e.g.
```
let aa;
let bb;
function foo() {
return [1, 2];
}
[aa, bb] = foo();  // jslint previously would warn here
```
this PR will additionally:
- ci - Replace npm-package used to auto-build vscode-plugin, vsce to @vscode/vsce.
> Branch destructure after function

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- jslint_ci.sh
- package.json
- ci - Add shell-functions shGitPullrequestCleanup(), shGitPullrequest() to automatically cleanup or create-and-push github-pull-commit to origin/alpha.
- jslint - Allow destructuring-assignment after function-definition.
- ci - Replace npm-package used to auto-build vscode-plugin, vsce to @vscode/vsce.
- test - Update test-function jstestDescribe() to wait awhile for imports to initialize before running tests.
- ci - Fix tmpdir in shell-function shBrowserScreenshot().
- vim - Allow installing vim-plugin to any directory, instead of hardcoded to ~/.vim/.
- ci - Update github-ci for actions/cache, actions/setup-python from nodejs v16 to nodejs v20.
- ci - Update shell-function shRollupFetch() to fix blank date-committed.
- ci - bugfix - Fix google-chrome unable to create screenshot because …
> # v2024.3.26

- .ci.sh
- CHANGELOG.md
- README.md
- jslint.mjs
- package.json
- coverage - Fix coverage-function v8CoverageReportCreate() throwing error EINVAL in latest nodejs-security-patch, when running win32-coverage with npm.cmd.
- jslint - Remove unnecessary shell-function shCurlExe().
> # v2024.6.28
